dist: jammy
language: python
python:
  - "3.10"

install:
  # Install Miniconda
  - export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda3;
  - wget ${CONDA_BASE}-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Create environment
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set show_channel_urls True
  - conda update --quiet conda
  - conda env create -f environment.yml
  - conda init
  - conda activate THOR
  # Output debug info
  - conda list
  - conda info -a

  # Install
  - pip install .

# command to run tests
script:
  - python -m pytest --verbose --color=yes -s --cov=thor

env:
  - CODECOV_TOKEN=0ef6a6d6-81a3-4af9-bdc5-5bd2db1e0065

after_success:
  - codecov